/* Auto-generated by genmsg_cpp for file /home/ludo/workspace/rosbuild_ws/humanoid_stack/humanoid_msgs/humanoid_nav_msgs/msg/ExecFootstepsAction.msg */
#ifndef HUMANOID_NAV_MSGS_MESSAGE_EXECFOOTSTEPSACTION_H
#define HUMANOID_NAV_MSGS_MESSAGE_EXECFOOTSTEPSACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "humanoid_nav_msgs/ExecFootstepsActionGoal.h"
#include "humanoid_nav_msgs/ExecFootstepsActionResult.h"
#include "humanoid_nav_msgs/ExecFootstepsActionFeedback.h"

namespace humanoid_nav_msgs
{
template <class ContainerAllocator>
struct ExecFootstepsAction_ {
  typedef ExecFootstepsAction_<ContainerAllocator> Type;

  ExecFootstepsAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  ExecFootstepsAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::humanoid_nav_msgs::ExecFootstepsActionGoal_<ContainerAllocator>  _action_goal_type;
   ::humanoid_nav_msgs::ExecFootstepsActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::humanoid_nav_msgs::ExecFootstepsActionResult_<ContainerAllocator>  _action_result_type;
   ::humanoid_nav_msgs::ExecFootstepsActionResult_<ContainerAllocator>  action_result;

  typedef  ::humanoid_nav_msgs::ExecFootstepsActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::humanoid_nav_msgs::ExecFootstepsActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ExecFootstepsAction
typedef  ::humanoid_nav_msgs::ExecFootstepsAction_<std::allocator<void> > ExecFootstepsAction;

typedef boost::shared_ptr< ::humanoid_nav_msgs::ExecFootstepsAction> ExecFootstepsActionPtr;
typedef boost::shared_ptr< ::humanoid_nav_msgs::ExecFootstepsAction const> ExecFootstepsActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace humanoid_nav_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a2c4888b786ce4d1be346c228ea5a28";
  }

  static const char* value(const  ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1a2c4888b786ce4dULL;
  static const uint64_t static_value2 = 0x1be346c228ea5a28ULL;
};

template<class ContainerAllocator>
struct DataType< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "humanoid_nav_msgs/ExecFootstepsAction";
  }

  static const char* value(const  ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
ExecFootstepsActionGoal action_goal\n\
ExecFootstepsActionResult action_result\n\
ExecFootstepsActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: humanoid_nav_msgs/ExecFootstepsActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
ExecFootstepsGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: humanoid_nav_msgs/ExecFootstepsGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
humanoid_nav_msgs/StepTarget[] footsteps\n\
float64 feedback_frequency\n\
\n\
================================================================================\n\
MSG: humanoid_nav_msgs/StepTarget\n\
# Target for a single stepping motion of a humanoid's leg\n\
\n\
geometry_msgs/Pose2D pose   # step pose as relative offset to last leg\n\
uint8 leg                   # which leg to use (left/right, see below)\n\
\n\
uint8 right=0               # right leg constant\n\
uint8 left=1                # left leg constant\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
================================================================================\n\
MSG: humanoid_nav_msgs/ExecFootstepsActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
ExecFootstepsResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: humanoid_nav_msgs/ExecFootstepsResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
humanoid_nav_msgs/StepTarget[] executed_footsteps\n\
\n\
================================================================================\n\
MSG: humanoid_nav_msgs/ExecFootstepsActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
ExecFootstepsFeedback feedback\n\
\n\
================================================================================\n\
MSG: humanoid_nav_msgs/ExecFootstepsFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
humanoid_nav_msgs/StepTarget[] executed_footsteps\n\
\n\
\n\
";
  }

  static const char* value(const  ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExecFootstepsAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::humanoid_nav_msgs::ExecFootstepsAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::humanoid_nav_msgs::ExecFootstepsActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::humanoid_nav_msgs::ExecFootstepsActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::humanoid_nav_msgs::ExecFootstepsActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HUMANOID_NAV_MSGS_MESSAGE_EXECFOOTSTEPSACTION_H

